name: CalledWorkflow

on:
  workflow_call:
    inputs:
      FOO:
        required: true
        type: string
      BAR:
        required: false
        type: string
      BAZ:
        required: false
        type: string
      REASON:
        required: true
        type: string
jobs:
   check-variables-in-called-wf:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo BAZ : ${{ inputs.BAZ }} 
          echo BAZ from json : ${{ fromJSON(inputs.BAZ) }} 
      - name: parse variable true
        if: ${{ fromJSON(inputs.BAZ) == true }}
        run: echo "BAZ was true"
      - name: parse variable false
        if: ${{ fromJSON(inputs.BAZ) == false }}
        run: echo "BAZ was false"
      - name: parse boolean steps
        run: |
          echo "FOO: ${{ inputs.FOO }}"
          echo "BAR: ${{ inputs.BAR }}"
          echo "BAZ: ${{ inputs.BAZ }}"
          echo "REASON: ${{ inputs.REASON }}"
