name: Calling Sanitiser

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      reason:
        # Friendly description to be shown in the UI instead of 'reason'
        description: 'Reason for build'
        # Default value if no value is explicitly provided
        default: 'Test'
        # Input has to be provided for the workflow to run
        required: false
        
jobs:


  call-workflow:
    uses: dave99galloway/github-actions-issues/.github/workflows/input-sanitisation.yml@main
    with:
      test: ${{ github.events.inputs.reason }}
