name: Calling workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      reason:
        # Friendly description to be shown in the UI instead of 'reason'
        description: 'Reason for build'
        # Default value if no value is explicitly provided
        default: 'Test'
        # Input has to be provided for the workflow to run
        required: false
        
jobs:
  set-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code to get the env files
        uses: actions/checkout@v2
      - name: set-variables-step
        env:
          REASON: experiment
        run: |
          echo "print GITHUB_ENV at start"
          while IFS= read -r line; do
            echo $line
          done < $GITHUB_ENV
          
          echo "echo the .github dir"
          ls -lrtahR ${{ github.workspace }}/.github/

          echo " load the env file and echo each line"
          echo "REASON=${{ github.event.inputs.reason || env.REASON }}" >> $GITHUB_ENV
          while IFS= read -r line; do
            echo $line
            echo "$line" >> $GITHUB_ENV
          done < ${{ github.workspace }}/.github/workflows/example.env

          echo "print GITHUB_ENV at end"
          while IFS= read -r line; do
            echo $line
          done < $GITHUB_ENV
          

      - name: check-variables-step
        run: |
          echo "print GITHUB_ENV at start"

          while IFS= read -r line; do
            echo $line
          done < $GITHUB_ENV
          
          echo "print each var "
          echo "REASON:  ${{ env.REASON }}"
          echo "FOO:  ${{ env.FOO }} "
          echo "BAR: ${{ env.BAR }} "
          echo "BAZ:  ${{ env.BAZ }} "

    outputs:
      FOO: ${{ env.FOO }}
      BAR: ${{ env.BAR }}
      BAZ: ${{ env.BAZ }}
      REASON:  ${{ env.REASON }}

  check-variables:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
      - name: check-variables-step
        run: |
          echo "FOO: ${{ needs.set-variables.outputs.FOO }}"
          echo "BAR: ${{ needs.set-variables.outputs.BAR }}"
          echo "BAZ: ${{ needs.set-variables.outputs.BAZ }}"
          echo "REASON: ${{ needs.set-variables.outputs.REASON }}"

  call-workflow:
    needs: [set-variables, check-variables]
    uses: dave99galloway/github-actions-issues/.github/workflows/called-workflow.yml@main
    with:
      FOO: ${{ needs.set-variables.outputs.FOO }}
      BAR: ${{ needs.set-variables.outputs.BAR }}
      BAZ: ${{ needs.set-variables.outputs.BAZ }}
      REASON: ${{ needs.set-variables.outputs.REASON }}
